### ISSUE TITLE
More of memgraph lab issue/request (Query size limit)

### ISSUE THREAD

**Issue by Kevin-Mc-Callister** [memgraph/memgraph-platform#24]
Hello! I couldn't find the memgraph lab repo and this was probably the closest I could find.

I'm on LAB version 2.0.1 and I can't issue queries that are longer than 5000 characters. Is there any reason for this? Is it configurable?
Could it be made configurable? (In the mean time I've been using the CLI but would love to use the beautiful lab aswell)

I would be happy to move this question/issue wherever it makes sense. Thanks!

**Comment by tonilastre** [comment]
Hi Arturo! Thanks for reaching out!

> I'm on LAB version 2.0.1 and I can't issue queries that are longer than 5000 characters. Is there any reason for this? Is it configurable?

There is actually no particular reason for 5000 characters, it was chosen as a 5x of the usual query length. Unfortunately, it is not configurable, but it is a good suggestion to add that as a configurable parameter. In the short term, we can definitely increase that and release the new version? 

How long are the queries that you are running through Lab? If those are longer than 5000 characters I am curious to know what kind of queries are those? Dataset building queries?

_Sorry for a lot of follow-up questions, I just want to get to know how are you using the Lab so we add/fix features to improve your experience and usage of it._

Thanks!

**Comment by ArtruneTranspara** [comment]
Hello! Thank you for your prompt answer.

The queries we are currently running are definitely not as long but for testing it would be awesome - sometimes it's just unwinding a list or want to test scale with X more items in the list.
It's not a single or particular query but I've reached that threshold probably twice in the last month and just went to mgconsole instead. (But not as cool, no history, etc)

**Comment by tonilastre** [comment]
Thanks for the response!

In the next Lab release, we will expose a way for you to actually override the default limits and input the custom ones through environment variables. This will enable you to fine-tune it, e.g. increase the limit to match your limits.

I will let you know when it is out and how to override it. It should be out in the next couple of days.

> Note: For now, the override will only work when using the Lab within the `memgraph-platform` because that is the only way to override configurations via environment variables. In the future, we might expose this in the UI as well.

**Comment by tonilastre** [comment]
Hi @ArtruneTranspara,

The new `lab` (2.1.2) and `memgraph-platform` (2.3.1) are out. Now you can override some of the default limitations.

With the following command, the lab will use the new limit for the max length of Cypher query which is 10000:

```
docker run -it -p 7687:7687 -p 7444:7444 -p 3000:3000 -e APP_CYPHER_QUERY_MAX_LEN=10000 memgraph/memgraph-platform:2.3.1
```

You can also change other limitations, these are the names of the env variables along with their default values:

```
APP_CYPHER_QUERY_MAX_LEN=5000
APP_MODULE_NAME_MAX_LEN=1000
APP_MODULE_CONTENT_MAX_LEN=50000
APP_STREAM_NAME_MAX_LEN=500
APP_NODE_PROPERTY_MAX_LEN=1000
```

**Comment by ArtruneTranspara** [comment]
Hello @[tonilastre](https://github.com/tonilastre) thank you very much! will test it out soon.
