### ISSUE TITLE
memgraph-lab no longer starts. Node is not installed.

### ISSUE THREAD

**Issue by ericmaino** [memgraph/memgraph-platform#34]
Seems that the latest refactoring in #31 broke the docker builds. Node is not installed on the image which prevents the service from starting.

I confirmed by using that the prior published docker image `2.6.1-memgraph2.5.0-lab2.4.0-mage1` does not have this issue.

**Comment by katarinasupe** [comment]
@ericmaino, thank you for the bug report. Closing the issue since it was resolved with the next Memgraph Platform release -`memgraph/memgraph-platform:2.6.2-memgraph2.5.0-lab2.4.0-mage1.5`.
